"""empty message

Revision ID: 50443cf37be3
Revises: d248c7f25f80
Create Date: 2020-05-24 11:49:10.682190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50443cf37be3'
down_revision = 'd248c7f25f80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), server_default='f', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
