"""added 'Attempt' and 'Quiz' tables

Revision ID: 9583639775c6
Revises: 4f5562f2d743
Create Date: 2020-05-21 13:43:20.603933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9583639775c6'
down_revision = '4f5562f2d743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('filename', sa.String(length=32), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_index(op.f('ix_quiz_category'), 'quiz', ['category'], unique=True)
    op.create_index(op.f('ix_quiz_date_added'), 'quiz', ['date_added'], unique=False)
    op.create_table('attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempt_date'), 'attempt', ['date'], unique=False)
    op.create_index(op.f('ix_attempt_score'), 'attempt', ['score'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attempt_score'), table_name='attempt')
    op.drop_index(op.f('ix_attempt_date'), table_name='attempt')
    op.drop_table('attempt')
    op.drop_index(op.f('ix_quiz_date_added'), table_name='quiz')
    op.drop_index(op.f('ix_quiz_category'), table_name='quiz')
    op.drop_table('quiz')
    # ### end Alembic commands ###
