"""added unique name for Quiz model

Revision ID: d248c7f25f80
Revises: 9583639775c6
Create Date: 2020-05-23 13:10:59.596886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd248c7f25f80'
down_revision = '9583639775c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz', sa.Column('quizname', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_quiz_quizname'), 'quiz', ['quizname'], unique=True)
    op.drop_index('ix_quiz_category', table_name='quiz')
    op.create_index(op.f('ix_quiz_category'), 'quiz', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_category'), table_name='quiz')
    op.create_index('ix_quiz_category', 'quiz', ['category'], unique=1)
    op.drop_index(op.f('ix_quiz_quizname'), table_name='quiz')
    op.drop_column('quiz', 'quizname')
    # ### end Alembic commands ###
