"""added date_joined field to User

Revision ID: 3891268227a2
Revises: b410ac4555b4
Create Date: 2020-05-25 13:48:59.520293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3891268227a2'
down_revision = 'b410ac4555b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_joined', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_date_joined'), 'user', ['date_joined'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_date_joined'), table_name='user')
    op.drop_column('user', 'date_joined')
    # ### end Alembic commands ###
