"""new db

Revision ID: b410ac4555b4
Revises: 
Create Date: 2020-05-24 15:54:17.435199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b410ac4555b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('quizname', sa.String(length=32), nullable=True),
    sa.Column('filename', sa.String(length=32), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_index(op.f('ix_quiz_category'), 'quiz', ['category'], unique=False)
    op.create_index(op.f('ix_quiz_date_added'), 'quiz', ['date_added'], unique=False)
    op.create_index(op.f('ix_quiz_quizname'), 'quiz', ['quizname'], unique=True)
    op.create_table('attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempt_date'), 'attempt', ['date'], unique=False)
    op.create_index(op.f('ix_attempt_score'), 'attempt', ['score'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attempt_score'), table_name='attempt')
    op.drop_index(op.f('ix_attempt_date'), table_name='attempt')
    op.drop_table('attempt')
    op.drop_index(op.f('ix_quiz_quizname'), table_name='quiz')
    op.drop_index(op.f('ix_quiz_date_added'), table_name='quiz')
    op.drop_index(op.f('ix_quiz_category'), table_name='quiz')
    op.drop_table('quiz')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
